#!/usr/bin/env python3
"""Generate pydoc HTML docs and a markdown index for top-level modules."""

from __future__ import annotations

import ast
import os
import subprocess
import sys
import tempfile
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_DIR = REPO_ROOT / "docs"
PYDOC_DIR = DOCS_DIR / "pydoc"
API_INDEX_PATH = DOCS_DIR / "API_REFERENCE.md"

STUB_MODULES = [
    "numpy",
    "scipy",
    "scipy.sparse",
    "scipy.spatial",
    "scipy.spatial.distance",
    "scipy.io",
    "sklearn",
    "sklearn.cluster",
    "sklearn.decomposition",
    "sklearn.manifold",
    "sklearn.metrics",
    "sklearn.metrics.pairwise",
    "sklearn.model_selection",
    "sklearn.neighbors",
    "sklearn.preprocessing",
    "torch",
    "torch.nn",
    "torch.nn.functional",
    "torch.nn.parameter",
    "torch.optim",
    "torch.utils",
    "torch.utils.data",
    "torch_geometric",
    "torch_geometric.nn",
    "matplotlib",
    "matplotlib.pyplot",
    "seaborn",
]

STUB_CONTT = '''"""Auto-generated pydoc stub module."""

class _StubMeta(type):
    def __getattr__(cls, name):
        return _StubType


class _StubType(metaclass=_StubMeta):
    def __init__(self, *args, **kwargs):
        pass

    def __getattr__(self, name):
        return _StubType

    def __call__(self, *args, **kwargs):
        return _StubType()

    def __iter__(self):
        return iter(())


def __getattr__(name):
    return _StubType
'''


def get_top_level_modules(root: Path) -> list[Path]:
    modules = []
    for path in root.glob("*.py"):
        if path.name.startswith("_"):
            continue
        modules.append(path)
    return sorted(modules, key=lambda p: p.name.lower())


def module_description(module_path: Path) -> str:
    try:
        tree = ast.parse(module_path.read_text(encoding="utf-8"))
        doc = ast.get_docstring(tree)
        if doc:
            first_line = doc.strip().splitlines()[0].strip()
            if first_line:
                return first_line
    except Exception:
        pass
    return "No module docstring provided."


def build_stub_packages(stub_root: Path) -> None:
    for dotted in STUB_MODULES:
        parts = dotted.split(".")
        if len(parts) == 1:
            init_file = stub_root / parts[0] / "__init__.py"
        else:
            pkg_dir = stub_root.joinpath(*parts[:-1])
            pkg_init = pkg_dir / "__init__.py"
            pkg_init.parent.mkdir(parents=True, exist_ok=True)
            pkg_init.write_text(STUB_CONTT, encoding="utf-8")
            init_file = stub_root.joinpath(*parts) / "__init__.py"
        init_file.parent.mkdir(parents=True, exist_ok=True)
        init_file.write_text(STUB_CONTT, encoding="utf-8")


def run_pydoc_for_module(module_name: str, stub_root: Path) -> tuple[bool, str]:
    cmd = [sys.executable, "-m", "pydoc", "-w", module_name]
    env = dict(os.environ)
    prior = env.get("PYTHONPATH", "")
    env["PYTHONPATH"] = str(stub_root) if not prior else f"{stub_root}{os.pathsep}{prior}"
    proc = subprocess.run(cmd, cwd=REPO_ROOT, capture_output=True, text=True, env=env)
    if proc.returncode == 0:
        return True, ""
    stderr = (proc.stderr or proc.stdout or "").strip()
    return False, stderr


def write_markdown_index(entries: list[dict[str, str]], failed: list[dict[str, str]]) -> None:
    lines = [
        "# API Reference",
        "",
        "This file is generated by `scripts/generate_pydoc.py`.",
        "",
        "## Modules",
        "",
    ]
    for entry in entries:
        lines.append(f"- [`{entry['module']}`]({entry['html_rel_path']}) - {entry['description']}")

    if failed:
        lines.extend(["", "## Generation Warnings", ""])
        for item in failed:
            lines.append(f"- `{item['module']}`: {item['error']}")

    lines.append("")
    API_INDEX_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    PYDOC_DIR.mkdir(parents=True, exist_ok=True)

    modules = get_top_level_modules(REPO_ROOT)
    if not modules:
        print("No top-level Python modules found.")
        return 0

    entries: list[dict[str, str]] = []
    failed: list[dict[str, str]] = []

    with tempfile.TemporaryDirectory(prefix="pydoc_stubs_") as temp_dir:
        stub_root = Path(temp_dir)
        build_stub_packages(stub_root)

        for module_path in modules:
            module_name = module_path.stem
            ok, err = run_pydoc_for_module(module_name, stub_root)

            generated_html = REPO_ROOT / f"{module_name}.html"
            target_html = PYDOC_DIR / f"{module_name}.html"

            if generated_html.exists():
                if target_html.exists():
                    target_html.unlink()
                generated_html.replace(target_html)

            if not target_html.exists():
                message = err or "pydoc did not produce an HTML file."
                failed.append({"module": module_name, "error": message})
                continue

            if not ok and err:
                failed.append({"module": module_name, "error": err})

            entries.append(
                {
                    "module": module_name,
                    "html_rel_path": f"pydoc/{module_name}.html",
                    "description": module_description(module_path),
                }
            )

    write_markdown_index(entries, failed)

    print(f"Generated docs for {len(entries)} module(s).")
    if failed:
        print(f"Warnings for {len(failed)} module(s). See {API_INDEX_PATH}.")
    print(f"API index written to {API_INDEX_PATH}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
